### ISSUE TITLE
Aggregator `create core db` step fails with authentication.

### ISSUE THREAD

**Issue by michelescarlato** [michelescarlato/mdr_on_linux_server#2]
Despite the Postgres server having been completely re-installed and the last backup restored, still the containerized Aggregator experiences an authentication error in the `create-core-mdr-db` step.

```
michelescarlato@krang:~/gitrepo/mdr_on_linux_server/dockerfiles/MDR_Aggregator$ docker-compose up --remove-orphans create-core-mdr-db
Creating network "mdr_aggregator_default" with the default driver
Creating mdr-agg-create-core-mdr-db ... done
Attaching to mdr-agg-create-core-mdr-db
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   **** SETUP ****
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   transfer data =  False
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   create core =  True
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   create json =  False
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   do statistics =  False
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   do iec =  False
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   do indices =  False
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   **** UNHANDLED EXCEPTION ****
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | +++++++++++++++++++++++++++++++++++++++
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   ***ERROR*** MDR_Aggregator application aborted
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 08001: could not connect to server "aggs"
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | DETAIL: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
mdr-agg-create-core-mdr-db         | connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         |    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|222_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlDataReader.NextResult()
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
mdr-agg-create-core-mdr-db         |    at Npgsql.NpgsqlCommand.ExecuteNonQuery()
mdr-agg-create-core-mdr-db         |    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
mdr-agg-create-core-mdr-db         |    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
mdr-agg-create-core-mdr-db         |    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 452
mdr-agg-create-core-mdr-db         |    at MDR_Aggregator.MonDataLayer.SetUpTempFTWs(ICredentials credentials, String dbConnString, String fdw_schema, String source_db, List`1 source_schemas) in /app/LoggingHelpers/MonitorDataLayer.cs:line 63
mdr-agg-create-core-mdr-db         |    at MDR_Aggregator.Aggregator.AggregateData(Options opts) in /app/TopLevelClasses/Aggregator.cs:line 144
mdr-agg-create-core-mdr-db         |    at Program.<Main>$(String[] args) in /app/TopLevelClasses/Program.cs:line 62
mdr-agg-create-core-mdr-db         | +++++++++++++++++++++++++++++++++++++++
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db         | 12/07/2024 : 07:46 :   **** CLOSING LOG ****
mdr-agg-create-core-mdr-db         | 
mdr-agg-create-core-mdr-db exited with code 255
```

Please provide an analysis upon this error.

Troubleshooting suggested:

- swap to the MDR Test db environment (win2019 server) and verify that the error is not experienced.
- compare postgres configurations between the two servers (auth algorithm may be different, as I know in MDR Test postgres uses md5, while on the linux server there is scram-sha-256).

**Comment by eunpark-sys** [comment]
Dear @michelescarlato 

I am investigating on the issue that is currenlty going on the MDR_Aggregator data pipeline.
After increasing the log level on Postgres, I have been able to detect that the issue is currently related to the password use.

It seems that somehow a couple of DBs inherited the password used on the old version (running on Windows server 2019).

To quickly assess the changes, I restored that password.
But keep in mind that as soon as the other data pipeline will run, password authentication errors will pop-up because the docker images still are using the "new" postgres password defined for the linux version.

Before discovering the issue, I changed the auth algorithm to md5, as you pointed out (is the one running on the MDR_Test windows 2019 server), and at the moment postgres on Krang server is running with that configuration.

I will keep you posted on the execution of the following steps in the Aggregation pipeline.

**Comment by eunpark-sys** [comment]
I attach auth logs to confirm my analysis.
The password has been omitted.

[postgres.log](https://github.com/user-attachments/files/18047843/postgres.log)
